"""Adding new fields to user model.

Revision ID: 367db15ca834
Revises: eec32b20e423
Create Date: 2022-03-21 18:01:27.664735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367db15ca834'
down_revision = 'eec32b20e423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('biography', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url')
    op.drop_column('user', 'biography')
    # ### end Alembic commands ###
